"$schema" = "schemas/schema.json"
[default]
description = """
This permission set configures which
android package install features are by default exposed.

#### Granted Permissions

It allows all package install features.

"""

permissions = [
  "allow-install",
  "allow-check-permissions",
  "allow-request-permissions",
]
