"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-register-back-event",
  "allow-registerListener",
  "allow-remove-listener",
]
